name: Build SVG Artifacts

on:
  push:
    branches: ["p/gongfeng98/testSHA"]
  pull_request:
    branches: ["p/gongfeng98/testSHA"]
  workflow_dispatch:
    inputs:
      build_android:
        description: "Build Android"
        required: true
        default: true
        type: boolean
      build_ios:
        description: "Build iOS"
        required: true
        default: true
        type: boolean
      build_harmony:
        description: "Build HarmonyOS"
        required: true
        default: true
        type: boolean

jobs:
  build-ios:
    name: Build iOS
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3

      - name: Lint Podspec File
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            COMMIT_SHA="${{ github.event.pull_request.head.sha }}"
            echo "AAAA"
          else
            COMMIT_SHA="${{ github.sha }}"
            echo "BBBB"
          fi
          echo $COMMIT_SHA
          POD_VERSION=0.0.1-for-ci-test SERVAL_KIT_VERSION=COMMIT_SHA bundle exec pod spec lint svg/ServalSVG.podspec --verbose --skip-import-validation --allow-warnings
          echo "111"